[general]
diff_renderer.enabled = true
diff_renderer.command = ["delta"]
diff_renderer.feature_keys = { line-numbers = "L", keep-plus-minus-markers = "C", side-by-side = "S" }

[bindings]
root.move_up = ["ctrl+up"]
root.move_down = ["ctrl+down"]
root.move_up_line = ["up"]
root.move_down_line = ["down"]

root.discard = ["k"]
